server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilan99x/sample-config-store
          search-paths:
           - '*service'

service:
  url: http://localhost:9091/wed-nest/banquet/api/v1
  description: Banquet application
  version: 1.0.0

